const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.destroy,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Health: 0},
	{Bullet: 0},
	{Goblin: 0},
	{Fade: 0},
	{SparkFlash: 0},
	{DestroyOutsideLayout: 0},
	{spell: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Wizard: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{scoreCount: 0},
	{gameOverText: 0},
	{gameOverRestartButton: 0},
	{controlSchemeTips: 0},
	{whiteLine: 0},
	{Touch: 0},
	{Score: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Goblin: class extends self.ISpriteInstance {},
	SparkFlash: class extends self.ISpriteInstance {},
	spell: class extends self.ISpriteInstance {},
	Wizard: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	scoreCount: class extends self.ITextInstance {},
	gameOverText: class extends self.ITextInstance {},
	gameOverRestartButton: class extends self.IButtonInstance {},
	controlSchemeTips: class extends self.ITextInstance {},
	whiteLine: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {}
}